apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.cluster.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}    # port of service
      targetPort: {{ .Values.pod.port }}  # port of container in pod
  selector:
    app: {{ .Values.pod.name }}           # must same <labels: app> of pod (deployment.yaml)
