regions:
- global
- us-east-1
- us-east-2

account-blocklist:  # at least one account ID
- "random-account"

accounts:
  "734921941180": # nghiapn97
    filters:
      IAMUser:
      - nghiapn2
      IAMLoginProfile:
      - nghiapn2
      IAMUserAccessKey:
      - property: UserName
        value: nghiapn2
      IAMUserPolicyAttachment:
      - property: PolicyName
        value: IAMUserChangePassword
      - property: UserName
        value: nghiapn2

resource-types:
  excludes:
    - Budget
    - OSPackage