regions:
- global
- us-east-1
- us-east-2

account-blocklist:  # at least one account ID
- "random-account"

accounts:
  "734921941180": # danlv3
    filters:
      IAMUser:
      - danlv3
      IAMUserAccessKey:
      - property: UserName
        value: danlv3
      IAMGroup:
      - "admin_group"
      IAMUserPolicyAttachment:
      - property: PolicyName
        value: IAMUserChangePassword
      - property: UserName
        value: danlv3
      IAMPolicy:
      - property: Name
        value: policy_access_ec2

resource-types:
  targets:
  - IAMUserPolicyAttachment
  - IAMUserAccessKey
  - IAMUser
  - S3Bucket
  - IAMPolicy
  - IAMRole
  - IAMGroup
  - EC2Instance
  - EC2Volume
  - EC2SecurityGroup
